---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    # - name: "Creates directory"
    #   file:
    #     path: ~/web
    #     state: directory

    - name: Copy files to EC2 instance
      copy:
        src: ~/project/backend/artifact.tar.gz
        dest: ~/artifact.tar.gz

    - name: extractor presents
      apt:
        name:
          - gzip
          - unzip
          - tar
        state: present
      become: true

    - name: Extract final files
      unarchive:
        src: ~/artifact.tar.gz
        dest: ~/
        remote_src: yes

  roles:
    - deploy
