---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "Creates directory"
      file:
        path: ~/backend
        state: directory

    - name: Copy files to EC2 instance
      copy:
        src: ~/project/backend/artifact.tar.gz
        dest: ~/backend

    - name: "Get into backend folder"
      shell: cd ~/backend

    - name: "Decompress the file"
      - unarchive: src=artifact.tar.gz dest=~/backend

  roles:
    - deploy
