---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "Creates directory"
      file:
        path: ~/web
        state: directory

    - name: Copy files to EC2 instance
      copy:
        src: ~/project/backend/artifact.tar.gz
        dest: ~/web/artifact.tar.gz

    - name: extractor presents
      ansible.builtin.yum:
        name:
          - unzip
          - tar
        state: present
      become: true

    - name: Extract final files
      shell: tar -xvzf ~/web/artifact.tar.gz -C ~/web/
      remote_src: yes

  roles:
    - deploy
