---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "Creates directory"
      file:
        path: ~/web
        state: directory

    - name: Copy files to EC2 instance
      copy:
        src: ~/project/backend/artifact.tar.gz
        dest: ~/web/artifact.tar.gz

    - name: "Install tar"
      become: yes
      shell: apt install -y tar unzip

    - name: "Decompress the file"
      become: yes
      unarchive:
        src: ~/web/artifact.tar.gz
        dest: ~/web/
        mode: 755
        remote_src: yes

  roles:
    - deploy
