---

- name: "Creates directory"
  file:
    path: ~/web
    state: directory

- name: "Copy files to the EC2 instance"
  copy:
    src: ~/project/backend/artifact.tar.gz
    dest: ~/web/artifact.tar.gz

- name: "Extract files"
  unarchive:
    src: ~/web/artifact.tar.gz
    dest: ~/web
    remote_src: yes

- name: "Executing node"
  shell: npm install ~/web

- name: "Run backend"
  shell: cd ~/web && pm2 start npm -- start